# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [14]:
import numpy as np

list_squares=[100,110,115,120,125,130,135,140,145,150]
list_rooms=[1,2,3,4,5,6,7,8,9,10]
list_prices=[1000,1100,1200,1300,1400,1500,1600,1700,1800,1900]

my_array2=np.array([list_squares,list_rooms,list_prices])

print(my_array2)


[[ 100  110  115  120  125  130  135  140  145  150]
 [   1    2    3    4    5    6    7    8    9   10]
 [1000 1100 1200 1300 1400 1500 1600 1700 1800 1900]]


2. Transpose the array you have created, so that every line can represent features of one house.

In [13]:

my_array2.T
print(my_array2.T)

 

[[ 100    1 1000]
 [ 110    2 1100]
 [ 115    3 1200]
 [ 120    4 1300]
 [ 125    5 1400]
 [ 130    6 1500]
 [ 135    7 1600]
 [ 140    8 1700]
 [ 145    9 1800]
 [ 150   10 1900]]


3. Display the shape of the array and explain what it means.

In [8]:
shp=my_array2.shape
print("Shape of the array is",shp)
print("my_array is two dimentional array and it has 3 rows and 10 columns")

Shape of the array is (3, 10)
my_array is two dimentional array and it has 3 rows and 10 columns


4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [12]:
import numpy as np


def arr_of_01(row,col):
    my_array2=np.full((row,col),1)
    
    for i in range(1,row,2):
        for j in range(1,col,2):
            my_array2[i][j]=0
              
    return my_array2

row=int(input("Enter rows number"))
col=int(input("Enter columns number"))

arr_of_01(row,col)

Enter rows number 6
Enter columns number 5


array([[1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1]])