# <font color=blue>Assignments for "Mathematical Operations on NumPy Arrays"</font>

1. Load the array you saved in the previous lesson from the disk.

In [6]:
import numpy as np
erq_arr=np.load("Earthquakes2.npy")
erq_arr


array([[ 1.    ,  1.    ,  1.    ,  1.    ,  1.    ],
       [ 0.    , 37.4341, 35.852 ,  7.02  ,  4.1   ],
       [ 0.    , 37.6878, 37.4016, 10.27  ,  4.4   ],
       [ 0.    , 37.2003, 30.4376, 78.07  ,  4.    ],
       [ 0.    , 35.6846, 26.7266, 42.77  ,  4.5   ],
       [ 0.    , 36.4171, 28.6991, 14.86  ,  4.1   ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 36.9653, 27.7633,  6.93  ,  4.3   ],
       [ 0.    , 38.893 , 26.4483, 11.62  ,  4.2   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.4635, 36.3113, 15.29  ,  4.3   ],
       [ 0.    , 37.0201, 36.0845, 10.    ,  4.1   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ],
       [ 0.    , 38.357 , 44.8686, 10.05  ,  4.1   ],
       [ 0.    , 35.7018, 28

2. Display the mean and the standard deviation for each column.

In [7]:
print("mean of each column",erq_arr.mean(axis=0) )
# axis=0 all columns
# axis=1 all rows
print("standart deviation of each column",erq_arr.std(axis=0))

mean of each column [ 0.05     35.41254  31.105145 19.0195    4.23    ]
standart deviation of each column [ 0.21794495  7.94782002  8.83572219 18.73871326  0.80690768]


3. Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [37]:
print("shape of erq_arr",erq_arr.shape)
print("shape of new array",np.array([1,25,25,10,4]).shape)
subt_arr = erq_arr-np.array([1,25,25,10,4])
subt_arr

shape of erq_arr (20, 5)
shape of new array (5,)


array([[ 0.00000e+00, -2.40000e+01, -2.40000e+01, -9.00000e+00,
        -3.00000e+00],
       [-1.00000e+00,  1.24341e+01,  1.08520e+01, -2.98000e+00,
         1.00000e-01],
       [-1.00000e+00,  1.26878e+01,  1.24016e+01,  2.70000e-01,
         4.00000e-01],
       [-1.00000e+00,  1.22003e+01,  5.43760e+00,  6.80700e+01,
         0.00000e+00],
       [-1.00000e+00,  1.06846e+01,  1.72660e+00,  3.27700e+01,
         5.00000e-01],
       [-1.00000e+00,  1.14171e+01,  3.69910e+00,  4.86000e+00,
         1.00000e-01],
       [-1.00000e+00,  1.10535e+01,  6.21350e+00,  2.66800e+01,
         1.20000e+00],
       [-1.00000e+00,  1.21958e+01,  5.62410e+00,  4.03300e+01,
         8.00000e-01],
       [-1.00000e+00,  1.19653e+01,  2.76330e+00, -3.07000e+00,
         3.00000e-01],
       [-1.00000e+00,  1.38930e+01,  1.44830e+00,  1.62000e+00,
         2.00000e-01],
       [-1.00000e+00,  1.23773e+01,  1.13855e+01,  5.30000e-01,
         8.00000e-01],
       [-1.00000e+00,  1.08861e+01,  1.0695

4. Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [38]:
mult_arr=new_arr2*2
mult_arr

array([[ 0.00000e+00, -4.80000e+01, -4.80000e+01, -1.80000e+01,
        -6.00000e+00],
       [-2.00000e+00,  2.48682e+01,  2.17040e+01, -5.96000e+00,
         2.00000e-01],
       [-2.00000e+00,  2.53756e+01,  2.48032e+01,  5.40000e-01,
         8.00000e-01],
       [-2.00000e+00,  2.44006e+01,  1.08752e+01,  1.36140e+02,
         0.00000e+00],
       [-2.00000e+00,  2.13692e+01,  3.45320e+00,  6.55400e+01,
         1.00000e+00],
       [-2.00000e+00,  2.28342e+01,  7.39820e+00,  9.72000e+00,
         2.00000e-01],
       [-2.00000e+00,  2.21070e+01,  1.24270e+01,  5.33600e+01,
         2.40000e+00],
       [-2.00000e+00,  2.43916e+01,  1.12482e+01,  8.06600e+01,
         1.60000e+00],
       [-2.00000e+00,  2.39306e+01,  5.52660e+00, -6.14000e+00,
         6.00000e-01],
       [-2.00000e+00,  2.77860e+01,  2.89660e+00,  3.24000e+00,
         4.00000e-01],
       [-2.00000e+00,  2.47546e+01,  2.27710e+01,  1.06000e+00,
         1.60000e+00],
       [-2.00000e+00,  2.17722e+01,  2.1390